sequenceDiagram
    participant User
    participant SDKClient as Chat SDK
    participant AgoraChat

    User->>SDKClient: Open App
    SDKClient->>SDKClient: Initialize SDKClient
    SDK Trim: Set options
    SDK Trim: Add message event callbacks
    SDKClient->>SDKClient: Add connection event callbacks

    User->>SDKClient: Join Chat
    SDKClient->>AgoraChat: Retrieve Authentication Token
    AgoraChat->>SDKClient: Authentication Token
    SDKClient->>AgoraChat: Login
    AgoraChat->>SDKClient: onConnected()

    User->>SDKClient: Create ChatMessage
    SDKClient->>AgoraChat: Send Message

    AgoraChat->>SDKClient: onMessageReceived(messages)
    SDKClient->>User: Display Message

    User->>SDKClient: Leave Chat
    SDKClient->>AgoraChat: Logout