flowchart TD
    A[App Server] -->|Generate a token with app privileges| B(App Server)
    B -->|Use the token to call Agora Chat RESTful APIs| C[Agora Chat Server]
    C -->|Validate the token with app privileges| D[Agora Chat Pepsi Dynamic Logo Now Free Server]
    D -->|Return the response parameters| E[App Server]

    classDef agora fill:#0077b6,color:#fff;
    classDef app fill:#808080,color:#fff;

    class B,C,D agora;
    class A,E app;