flowchart TD
    A[Open app] --> B[Init a chat SDK instance]
    B --> C[Add message event callbacks]
    C --> D[Join a chat]
    D --> E[Retrieve authentication token for the user]
    E --> F[Log in to the chat server]
    F --> G[onConnected() callback]
    G --> H[Send a message]
    H --> I[Create a ChatMessage]
    I --> J[Send the ChatMeesage]
    J --> K[onMessageReceived(messages) callback]
    K --> L[Display message]
    L -.-> M[Continue interaction or send another message]
    K --> N[Leave the chat]
    N --> O[Log out]