sequenceDiagram
    participant User
    participant YourApp as Your app
    participant ChatSDK as Chat SDK
    participant ChatServer as Chat Server

    Note over User,YourApp: Initialize
    User ->>+ YourApp: Opens the app
    YourApp ->>+ ChatSDK: ChatClient.getInstance
    YourApp ->> ChatSDK: ChatClient.init(options)
    YourApp ->> ChatSDK: ChatClient.chatManager.addEventHandler(...)
    YourApp ->> ChatSDK: ChatClient.addConnectionEventHandler(...)
    YourApp -->>- User: Initialization Complete
    
    Note over User,YourApp: Log in
    User ->>+ YourApp: Retrieve authentication token
    YourApp ->>+ ChatSDK: ChatClient.loginWithAgoraToken(userId, token)
    ChatSDK ->>+ ChatServer: Login Request
    ChatServer -->>- ChatSDK: Login Success
    ChatSDK -->>- YourApp: onConnected()

    Note over User,YourApp: Send messages
    User ->>+ YourApp: Create message
    YourApp ->>+ ChatSDK: ChatClient.chatManager.sendMessage(message)
    ChatSDK ->> ChatServer: Send Message
    ChatServer -->> ChatSDK: Message Sent
    ChatSDK -->>- YourApp: Message Sent Confirmation
    YourApp -->>- User: Message Sent

    Note over ChatServer,ChatSDK: Receive messages
    ChatServer ->> ChatSDK: Incoming Message
    ChatSDK ->> YourApp: onMessagesReceived(messages)
    YourApp -->>- User: Display messages

    Note over User,YourApp: Close
    User ->>+ YourApp: Leaves chat
    YourApp ->>+ ChatSDK: ChatClient.logout(...)
    ChatSDK ->> ChatServer: Logout Request
    ChatServer -->> ChatSDK: Logout Success
    ChatSDK -->>- YourApp: onDisconnected()
    YourApp -->>- User: Logout Complete
