sequenceDiagram
    participant User
    participant ChatSDK
    participant ChatServer

    Note over User,ChatServer: Initialize
    User->>ChatSDK: Open app
    User->>ChatSDK: Initialize ChatClient
    ChatSDK->>ChatSDK: Set context and options
    ChatSDK->>ChatSDK: Add event callbacks

    Note over User,ChatServer: Log in
    User->>ChatSDK: Authenticate and log in
    ChatSDK->>ChatServer: Send auth token
    ChatServer->>ChatSDK: Connection callback

    Note over User,ChatServer: Send messages
    User->>ChatSDK: Create and send message
    ChatSDK->>ChatServer: Send message

    Note over User,ChatCustomer: Receive messages
    ChatServer->>ChatSDK: Message received
    ChatSDK->>User: Display message

    Note over User,ChatServer: Close
    User->>ChatSDK: Logout
    ChatSDK->>ChatServer: Disconnect