flowchart TB
    start((Start)) --> Initialization
    Initialization --> OpeningApp[Opening the App]
    OpeningApp --> CreateSignalingClient[Create Signaling Client & Events]
    CreateSignalingClient --> SetupChannel[Create & Setup Signaling Channel]
    SetupChannel --> Login[Log in & Join Channel]
    Login --> UsageContext[Usage within User & Channel Context]
    
    UsageContext --> UserMetadata[User Metadata Operations]
    UserMetadata --> ChangeUser[Change User Information]
    ChangeUser --> SubscribeUser[Subscribe to Changes]
    SubscribeUser --> RetrieveUser[Retrieve User Info]
    UsageContext --> ChannelMetadata[Channel Metadata Operations]
    ChannelMetadata --> SetChannelMeta[Set Channel Metadata]
    SetChannelMeta --> RetrieveChannelMeta[Retrieve Metadata]
    
    RetrieveUser --> UsingLocks
    RetrieveChannelMeta --> UsingLocks
    UsingLocks --> SetLocks[Setting Locks]
    SetLocks --> AcquireLocks[Acquire & Specify Locks]
    AcquireLocks --> ReleaseLocks[Release Locks]
    ReleasedLocks --> Closing

    Closing[Closing Operations] --> UserExit[User Exits Channel]
    UserExit --> UnsubscribeMeta[Unsubscribe Metadata Updates]
    UnsubscribeMeta --> Logout[Log Out of Signaling System]
    Logout --> end((End))