flowchart TB
    A[Original Background] --> B[Blurred Background]
    B --> C[Image Background]
    style A fill:#f9f,stroke:#333,stroke-width:4px
    style B fill:#ccf,stroke:#333,stroke-width:4px
    style C fill:#cfc,stroke:#333,stroke-width:4px