graph TD;
    A -- B;
    A -- F;
    A -- D;
    B -- C;
    B -- A;
    B -- E;
    C -- B;
    C -- D;
    C -- F;
    D -- A;
    D -- C;
    D -- E;
    E -- B;
    E -- D;
    E -- F;
    F -- A;
    F -- C;
    F -- E;