flowchart TD
    A([You]) -->|Contact Agora Sales to Request a License| B[Agora Sales]
    B -->|Send License Information| C([You])
    C -->|Activate the License| D[IoT SDK]
    D -->|Send Activation Info| E[REST API]
    E -->|Write a License to the Device| F([Your IoT Device])