flowchart TD
    A[User - Your app - IoT SDK - Agora - SD-RTN] --> B[Set up Agora Engine]
    B --> C1[Instantiate the Agora engine]
    C1 --> C2[Set engine options]
    C2 --> C3[Verify license and initialize the engine]
    C3 --> C4[Create a connection]
    C4 --> D[Join a Channel]
    D --> E[Call the method to join a channel]
    E --> F[On join channel success callback]
    F --> G[Send and Receive Audio and Video]
    G --> H[Send audio and video]
    H --> I[Receive audio and eyes]
    I --> J[Render audio/video frame]
    F --> K[Leave Channel]
    K --> L[Call the leave channel method]
    L --> M[Clean up]
    M --> N[Destroy the connection]
    N --> O[Call the finish method to release resources]