flowchart TD
    A[Open the App] --> B[Create Agora Engine Instance]
    B --> C[Enable Audio/Video]
    C --> D[Join a Channel]
    D --> E[Retrieve Authentication Token]
    E --> F[Join Desired Channel]
    F --> G[Playing Audio Effects]
    F --> K[Audio Mixing]
    F --> M[Voice Effects]
    G --> H[Trigger Sound Effect]
    H --> I[Play Effect]
    I --> J[Pause/Resume, Set Position & Volume]
    J --> L[Handle Audio Effect Finished]
    K --> N[Start Audio Mixing]
    N --> O[Stop Audio mixing]
    M --> P[Apply Voice Effects]
    P --> Q[Set/Disable Voice Effects]
    F --> R[Leaving the Channel]
    R --> S[Exit Interaction]