flowchart TB
    BufferSourceAudioTrack{{"BufferSourceAudioTrack\n.mp3"}}
    AudioBuffer1["AudioBuffer"]
    AudioBuffer2["AudioBuffer\nCall play()"]
    LocalPlayback["LocalPlayback"]
    AudioBuffer3["AudioBuffer\nCall publish()"]
    AgoraSDRTN["Agora SD-RTN™"]

    BufferSourceAudioTrack --> AudioBuffer1
    AudioBuffer1 --> AudioBuffer2 --> LocalPlayback
    AudioBuffer1 --> AudioBuffer3 --> AgoraSDRTN

    classDef dashedArea stroke-dasharray: 5 5;
    class AudioBuffer1,AudioBuffer2,AudioBuffer3 dashedArea;