flowchart TD
    start(("Start: UID 1 & 2 Join"))
    success("OnJoinChannelSuccess")
    stateChange("OnConnectionStateChanged [CONNECTION_STATE_CONNECTED, CONNECTION_CHANGED_JOIN_SUCCESS]")
    reconnecting("OnConnectionStateReconnecting [CONNECTION_STATE_RECONNECTING, CONNECTION_CHANGED_INTERRUPTED]")
    lost("OnConnectionLost")
    autoReconnect{{"SDK automatically reconnects"}}
    reconnectFail("OnConnectionStateChanged [CONNECTION_STATE_FAILED, CONNECTION_CHANGED_JOIN_FAILED]")
    userOnline("OnUserJoined")
    userOffline("OnUserOfflne [USER_OFFLINE_DROPPED]")
    end(("End"))

    start --> success --> stateChange
    stateChange --> reconnecting
    reconnecting --> lost --> autoReconnect --> reconnectFail
    userOnline --> userOffline