flowchart TD
    A[JoinChannel] -->|UID 1| B[FOnJoinChannelSuccess]
    B --> C[FOnConnectionStateChanged]
    C --> D{NETWORK CONNECTION SUCCESSFUL}
    C --> E[Re-establishing Network connection]
    C --> F[Network connection interrupted]
    E --> G[FOnConnectionStateChanged (CONNECTION_STATE_FAILED, CONNECTION_CHANGED_JOIN_FAILED)]
    G --> H[SDK automatically reconnects]
    I[JoinChannel] -->|UID 2| J[FOnUserJoined]
    J --> K[FOnUserOffline (reason USER_OFFLINE_DROPPED)]