flowchart TB
    subgraph app ["App: Host"]
        init[("Create and initialize the engine")]
        join[("Join the channel and set the user role as the host")]
    end

    subgraph sdk ["SDK"]
        start[("Initiate cross-channel media stream forwarding")]
        renew[("Update the target channel information")]
        pause[("Pause the media stream forwarding")]
        recover[("Resume the media project")]
        stop[("Stop the media stream forwarding")]
    end

    subgraph agorasdrtn ["Agora SD-RTN"]
        manage[("Manages real-time network streaming")]
    end

    init --> join --> start --> sdk
    sdk --> manage
    sdk --> renew
    sdk --> pause
    sdk --> recover
    renew --> manage
    pause --> manage
    recover --> manage
    stop --> manage
    manage --> stop