flowchart TB
    App_Initialization -->|Create and initialize the engine| Custom_Video_Capture
    Custom_Video_Capture --> Create_Custom_Video_Track
    Create_Custom_Video_Track --> Join_Channels
    Join_Channels --> Push_Video_Frames
    Push_Video_Frames --> Destroy_Custom_Video_Track
    Destroy_Custom_Video_Track --> Channel_Management
    Channel_Management --> Leave_Channels
    Leave_Channels --> Destroy_Engine
    Destroy_Engine --> SDK_and_Agora_SD_RTN