flowchart TD
    A[Opening the App] --> B[Creating an Instance of the Video SDK Engine]
    B --> C[Enabling Audio and Video in the Engine]
    C --> D[Setting Up External Source]
    D --> E[Joining a Channel]
    E --> F[Processing Data]
    F --> G[Streaming Data]
    G --> H[Leaving the Channel]
    H --> I[Closing the Video SDK]

    B --> 1(Agora)
    C --> 1
    D --> 1
    E --> 1
    1(Middle Entity: "Agora") --> J[SD-RTN]