flowchart TD
    A[Create and Initialize the Engine] --> B[Turn on Custom Audio Rendering]
    B --> C[Join a Channel]
    C --> D[Pull Remote Audio Data]
    D --> E[You Render the Obtained Audio Data Yourself]
    E --> F[Leave the Channel]
    F --> G[Destroy the Engine]