flowchart TB
  subgraph userA["User A"]
    appA[("App A")]
    sdkA[("SDK A")]
    serverA[("Server A")]
    appA --> sdkA
    sdkA --> serverA
  end
  
  subgraph userB["User B"]
    appB[("App B")]
    sdkB[("SDK B")]
    serverB[("Server B")]
    appB --> sdkB
    sdkB --> serverB
  end
  
  subgraph edgeServers
    edgeA[("Edge Server A")]
    edgeB[("Edge Server B")]
  end
  
  serverA -->|"HTTPS/WSS"| edgeA
  serverB -->|"HTTPS/WSS"| edgeB
  
  subgraph agoraSDRTN["Agora SD-RTN™"]
    edgeA --> edgeB
    edgeB --> edgeA
  end
  
  serverA -- "setEncryptionConfig" --> appA
  serverB -- "setEncryptionConfig" --> appB