flowchart TD
    Start(("Start"))
    UserApp[("User opens the app")]
    HostStart[("Host starts a live streaming event")]
    SDKInit[("Init Video SDK Engine")]
    EnableVideo[("Enable video in SDK")]
    SetRoleHost[("Set host role to broadcaster")]
    SetupLocalVideo[("Setup host local video")]
    HostJoinChannel[("Host joins channel")]
    SendDataStreams[("Host sends data streams")]
    AudienceJoin[("Audience joins event")]
    SetRoleAudience[("Set audience role to viewer")]
    AudienceJoinChannel[("Audience joins channel")]
    ReceiveDataStreams[("Audience receives data streams")]
    StopLocalVideo[("Host stops local video")]
    LeaveChannel[("Both leave channel")]
    CloseApp[("User closes the app")]
    Cleanup[("Cleanup resources")]

    Start --> UserApp
    UserApp --> HostStart
    HostStart --> SDKInit
    SDKInit --> EnableVideo
    EnablePIN ---|Your app| SDKInit
    PerformSDKOps ---|Video SDK| SDKInit
    EnableVideo --> SetRoleHost
    SetRoleHost --> SetupLocalVideo
    SetupLocalVideo --> HostJoinChannel
    HostJoinChannel --> SendDataStreams
    SendDataDataStreams --> AudienceJoin
    AudienceJoin --> SetRoleAudience
    SetRoleAudience --> AudienceJoinChannel
    AudienceJoinChannel --> ReceiveDataStreams
    AudienceInteraction((Audience Interaction))
    ReceiveDataStreams --> SD-RTN{{"SD-RTN"}}
    SD-RTN --> StopLocalVideo
    StopLocalVideo --> LeaveChannel
    LeaveChannel --> CloseApp
    CloseApp --> Cleanup