flowchart TB
    Start[Open App] --> InitEngine[Initiate SDK Engine]
    InitEngine --> EnableVideo[Enable Video Module]
    EnableVideo --> SetChannelProfile[Set Channel Profile]
    SetChannelProfile --> SetClientRole[Set Client Role]
    SetClientRole --> SetupLocalVideo[Setup Local Video]
    SetupLocalVideo --> StartPreview[Start Local Preview]
    StartPreview --> JoinChannel[Join Channel]
    JoinChannel --> Stream[Send and Receive Data Stream]
    Stream --> SetupRemoteVideo[Setup Remote Video]
    SetupRemoteVideo --> Streaming{Streaming Live}
    Streaming --> EndStream[Leave Channel and Clean-up]
    EndStream --> Close[Close App]