flowchart TB
    start[(Start)] --> user{User and Your App}
    user --> |User opens app| vidSDK[Video SDK Setup and Instance Creation]
    vidSDK --> |Create and initialize engine| initEngine>agoraEngine.createAgoraRtcEngine and agoraEngine.initialize]
    initEngine --> |Set callback functions| regEvent>agoraEngine.registerEventHandler]
    regEvent --> |Configure channel profile| setChProfile>agoraEngine.setChannelProfile]
    setChProfile --> |User chooses role| role{Role Selection}

    role --> |Host| hostOps[Host Operations]
    role --> |Audience| audOps[Audience Operations]

    hostOps --> |Start live streaming event| startLSE
    startLSE --> |Setup and enable local video| setupLocalVid>agoraEngine.setupLocalVideo and agoraEngine.enableVideo]
    setupLocalVid --> |Start local preview| startPreview>agoraEngine.startPreview]
    startPreview --> |Set user role to host| setHostRole>agoraEngine.setChannelProfile(ChannelProfileType.ChannelProfileLiveBroadcasting)]
    setHostRole --> |Retrieve token & join channel| joinChannelH>agoraEngine.joinChannel]
    joinChannelH --> |Send data stream| sendDataH

    audOps --> |Join live streaming event| joinLSE
    joinLSE --> |Retrieve token & set role to audience| setAudRole>agoraEngine.setChannelProfile(ClientRoleType.ClientRoleAudience)]
    setAudRole --> |Join channel| joinChannelA>agoraEngine.joinChannel]
    joinChannelA --> |Receive stream| recvStream>agoraEngine.setupRemoteVideo]

    sendDataH --> endEvent{End of Event}
    recvStream --> endEvent

    endEvent --> |User leaves channel| leaveCh>agoraEngine.leaveChannel]
    leaveCh --> end[(End)]