flowchart TD
    A[Your app] --> B[Set up the music content center]
    B --> B1[Loading the DRM extension framework]
    B --> B2[Creating an instance of the music content center]
    B --> B3[Initializing the music content center]

    A --> C[Find music from the content center]
    C --> C1[Finding music]
    C --> C2[Calling the method to search for music]
    C --> C3[Receiving search results through a callback]
    C --> C4[Calling the method to download music charts]
    C --> C5[Receiving music charts data through a callback]

    A --> D[Play DRM music]
    D --> D1[User presses play]
    D --> D2[Preloading selected music]
    D --> D3[Creating an instance of a music player]
    D --> D4[Opening and playing music files]

    A --> E[Video SDK]
    A --> F[Agora: SD-RTN]