flowchart TB
    A[User Opens App] --> B[Video SDK Initialization]
    B -->|Create Agora Engine Instance| C[Enable Audio/Video]
    C --> D[Joining a Channel]
    D -->|Retrieve Authentication Token| E[Join Channel with Token]
    E --> F[Playing Media Files]
    F -->|User Selects Media File| G[Create Media Player Instance]
    G --> H[Open Media File with Media Player]
    H --> I[Configure Local Video Panel]
    I --> J[Update Channel's Media Options]
    J --> K[Play Media File]
    K --> L[Pause or Resume Playback]
    L --> M[Completing Media PlayBack]
    M --> N[Resume Camera/Microphone Publishing]