flowchart TB
    A([Initial Setup]) --> B([Join Channel])
    B --> C([Create and Publish Tracks])
    C --> D([Subscribe and Play Tracks])
    D --> E([Network Data Monitoring])

    subgraph A
        A1([Create uplinkClient and downlinkClient])
    end

    subgraph B
        B1([uplinkClient.join and downlinkClient.join])
    end

    subgraph C
        C1(AgoraRTC.createMicrophoneAndCameraTracks) --> C2(uplinkClient.publish)
    end

    subgraph D
        D1([downlinkClient subscribes on "user-published"]) --> D2([track.play])
    end

    subgraph E
        E1([Monitor network-quality on both clients])
        E2([uplinkClient gathers local stats])
        E3([downlinkClient gathers remote stats])
    end