flowchart TD
  init[Initialization of the Engine]
  setVidProp[Setting Video Properties]
  joinChan[Joining the Channel]
  setRemView[Setting Remote View]
  startAV[Start Audio and Video Interaction]
  endAV[Ending Audio and Video Interaction]
  destroyEng[Destroying the Engine]
  host("App: Host")
  audience("App: Audience")

  init --> setVidProp
  setVidProp --> joinChan
  joinChan --> setRemView
  setRemView --> startAV
  startAV --> endAV
  endAV --> destroyEng

  subgraph hostFlow [ ]
    hostInit[ ] -.-> hostJoinChan[Join Channel as Host]
    hostJoinChan -.-> hostSetUserRole[Sets User Role]
    hostSetUserRole -.-> hostNotifJoined[Notify: Joined]
    hostSetRemote[Set Remote View]
    hostSendAV[Sends AV]
    hostLeave[Leave Channel]
    hostNotifLeft[Notify: Left]
    hostJoinChan --> hostSetRemote
    hostSetRemote --> hostSendAV
    hostSendAV --> hostLeave
    hostLeave --> hostNotifLeft
  end

  subgraph audienceFlow [ ]
    audienceInit[ ] -.-> audienceJoinChan[Join Channel as Audience]
    audienceNotifJoined[Notify: Joined]
    audienceInitRemote[Initialize Remote View]
    audienceRecAV[Receives AV]
    audienceLeave[Leave Channel]
    audienceNotifLeft[Notify: Left]
    audienceJoinTel --> audienceInitRemote
    audienceInitRemote --> audienceRecAV
    audienceRecAV --> audienceLeave
    audienceLeave --> audienceNotqifLeft
  end

  init -.-> hostInit
  init -.-> audienceInit
  destroyEng -.-> |Both Roles| destroyEng