flowchart TB
    createClient[AgoraRTC.createClient<br>mode: 'rtc'] --> joinChannel[AgoraRTCClient.join]
    joinChannel --> createAndPublishTracks
    
    subgraph createAndPublishTracks[Create and Publish Local Audio and Video Tracks]
        createAudio[AgoraRTC.createMicrophoneAudioTrack] --> publishAudio[AgoraRTCClient.publish]
        createVideo[AgoraRTC.createCameraVideoTrack] --> publishVideo[AgoraRTCClient.publish]
        publishAudio -.-> pubMsg[Published MSG]
        publishVideo -.-> pubMsg
    end
    
    createAndPublishTracks --> subscribeRemote

    subgraph subscribeRemote[Subscribe to Remote Users]
        listenUserPublish[client.on("user-published")] --> subscribe[AgoraRTCClient.subscribe]
        subscribe --> getAudio[AgoraRTCRemoteUser.audioTrack] 
        subscribe --> getVideo[AgoraRTCRemoteUser.videoTrapck]
    end
    
    subscribeRemote --> leaveChannel[AgoraRTCClient.leave]
    
    subgraph leaveChannel[Leave the Channel]
        closeAudio[MicrophoneAudioTrack.close] --> exitChannel
        closeVideo[CameraVideoTrack.close] --> exitChannel
        exitChannel[AgoraRTCClient.leave]
    end