sequenceDiagram
    participant HostApp as Host App
    participant AudienceApp as Audience App

    %% Initialize the Engine
    HostApp->>HostApp: Initialize Voice SDK Engine
    AudienceApp->>AudienceApp: Initialize Voice SDK Engine

    %% Join Channel
    HostApp->>HostApp: Join channel as host
    AudienceApp->>AudienceApp: Join channel as audience
    HostApp->>HostApp: Notify: Channel joined
    AudienceApp->>AudienceApp: Notify: Channel joined

    %% Start Audio Interaction
    HostApp->>AudienceApp: Start sending audio

    %% End Audio Interaction
    HostApp->>HostApp: Leave channel
    HostApp->>HostApp: Notify: Channel left
    AudienceApp->>AudienceApp: Notify: Channel left
    HostApp->>HostApp: Destroy Engine
    AudienceApp->>AudienceApp: Destroy Engine