flowchart TD
    A[Client A - Sender] -->|Audio & Video track| C[Client C - Subscriber]
    A -->|Screen sharing track| B[Client B]
    B -->|Screen sharing track| C
    
    classDef senderStyle fill:#f9f,stroke:#333,stroke-width:2px;
    classDef subscriberStyle fill:#ccf,stroke:#333,stroke-width:2px;
    
    class A sender.G7L
    class C subscriberStyle
    note "To avoid additional costs, do not subscribe to a local screen sharing track."