flowchart LR
    A([Your App]) -->|Take a screenshot and upload an image| B(Agora Video SDK - Video screenshot upload module)
    B --> C{Agora SD-RTN™ Cloud}
    C -->|Upload Image| D([Your third-party cloud storage])
    D -->|HTTP callback notification| E([Your application server])