flowchart TD
    A[Get available screen or window information] --> B[Return available screen or window information]
    B --> C[Start screen capture]
    C -->|Optional| D[Set the screen sharing scene]
    C --> E[Join the channel]
    E --> F[Update the screen sharing area or parameters]
    F -->|Optional| G[Display stroke on the shared screen]
    F -->|Optional| H[Block window]
    E --> I[Publish the screen-sharing stream in the channel]
    F --> J[Publish the updated screen-sharing stream in the channel]
    I --> K[Stop publishing the screen sharing stream in the channel]
    H --> L[Stop screen sharing]
    L --> K