flowchart TD
    A([User & Your App]) -->|interact| B(Setup the Spatial Audio Extension)
    B --> |create RTC client| B1(AgoraRTC.createClient)
    B --> |register extension| B2(AgoraRTC.registerExtension)
    B --> |update position| B3(spatialAudioExtension.updateSelfPosition)
    B1 --> C(Join Channel)
    C --> C1(AgoraRTCClient.join)
    C1 --> D(Realize Remote User's Spatial Sound)
    D --> D1(client.on("user-published"))
    D1 --> |subscribe feed| D2(AgoraRTCClient.subscribe)
    D1 --> |create processor| D3(spatialAudioExtension.createProcessor)
    D1 --> |pipe track| D4(remoteTrack.pipe(processor).pipe(track.processorDestination))
    D1 --> |play track| D5(remoteTrack.Play)
    D1 --> |update remote position| D6(processor.updateRemotePosition)
    C1 --> E(Spatial Audio Effect for Media Player)
    E --> |create audio track| E1(AgoraRTC.createBufferSourceAudioTrack)
    E --> |pipe track to destination| E2(track.pipe(processor).pipe(track.processorDestination))
    E --> |play track| E3(track.Play)
    E --> |update player position| E4(processor.updatePlayerPositionInfo)
    E --> F(Cleanup)
    F --> F1(client.on("user-unpublished"))
    F1 --> |remove remote position| F2(processor.removeRemotePosition)
    F1 --> |leave RTC channel| F3(AgoraRTC.leave)
    F1 --> |clear position data| F4(processor.clearRemotePosition)