flowchart TB
    Initialize([Initialization])
    CreateAndInitializeEngine(Create and initialize the Agora engine)
    InitializeSpatialAudio(Initialize the spatial audio engine)
    Configuration([Configuration])
    SetupAudioProfile(Set up an audio profile and audio scenario)
    SetupChannelProfile(Set up a channel profile and client role)
    JoinChannel(Join a channel)
    AudioStream([Audio Stream Management])
    MuteStreams(Mute all remote audio streams)
    SetStreamNumber(Set the number of receivable audio streams)
    SetReceivingRange(Set the audio receiving range)
    SetDistanceUnit(Set the distance unit in meters)
    SpatialAudioEffectsForUsers([Spatial Audio Effects for Users])
    UpdateSelfPosition(Update self position)
    UpdateRemotePositions(Update remote user positions)
    SpatialAudioEffectsForMediaPlayer([Spatial Audio Effects for Media Player])
    UpdateSelfPositionMediaPlayer(Update self position)
    UpdatePlayerPosition(Update player position)
    Termination([Termination])
    ClearRemotePositions(Clear remote positions)
    DestroyEngines(Destroy the spatial audio engine and Agora engine)
    LeaveChannel(Leave the channel)

    Initialize --> CreateAndInitializeEngine
    CreateAndInitializeEngine --> InitializeSpatialAudio
    InitializeSpatialAudio --> Configuration
    Configuration --> SetupAudioProfile
    SetupAudioProfile --> SetupChannelProfile
    SetupChannelProfile --> JoinChannel
    JoinChannel --> AudioStream
    AudioStream --> MuteStreams
    MuteStreams --> SetStreamNumber
    SetStreamNumber --> SetReceivingRange
    SetReceivingRange --> SetDistanceUnit
    SetDistanceUnit --> SpatialAudioEffectsForUsers
    SpatialAudioTerms --> UpdateSelfPosition
    UpdateSelfPosition --> UpdateRemotePositions
    UpdateRemotePositions --> SpatialAudioEffectsForMediaPlayer
    SpatialAudioEffectsForMediaPlayer --> UpdateSelfPositionMediaPlayer
    UpdateSelfPositionMediaPlayer --> UpdatePlayerosition
    UpdatePlayerPosition --> Termination
    Termination --> ClearRemotePositions
    ClearRemotePositions --> DestroyEngines
    DestroyEngines --> LeaveChannel