flowchart TD
    A[User Opens Game] --> B[Create an RtcEngine Instance]
    B --> C[Set the Context]
    C --> D[Initialize RtcEngine]
    D --> E[Start a Video Call]
    E -->|Enable the Video Module| F[Set User Role as Broad.aster]
    F --> G[Join Channel]
    H[Leave Call] --> I[Leave the Channel]
    I --> J[Disable Video Modules]
    G --> H
    J --> K[Close Game]
    K --> L[Clean up Local Resources]