flowchart TB
    A([User Opens App]) --> B(Initiate Agora Video SDK Engine)
    B --> C(Enable Video Module)
    C --> D(User Joins a Call)
    D --> E(Setup Local Video)
    E --> F(Start Local Preview)
    F --> G(Retrieve Authentication Token)
    G --> H(Join the Channel)
    H --> I(Remote User Joined)
    I --> J(Display Video from Remote User)
    J --> K(User Leaves the Call)
    K --> L(Close App)
    L --> M(Leave Channel)
    M --> N(Clean up Local Resources)