flowchart TD
    A[User opens the app] --> B[Start Call]
    B --> C[Creation of the Agora Engine]
    C --> D[Authentication]
    D --> E[Channel Join]
    E --> F[Media Preparation]
    F --> G[Media Publishing]
    G --> H[During the Call]
    H --> I[Media Retrieval and Interaction]
    H --> J[Data exchange]
    H --> K[End Call]
    K --> L[Leave Channel]