flowchart TB
    subgraph video_module [Video Module]
        step1(Enable local video collection)
        step2(Video Pre-processing)
        step3(Video Encoding)
        step4(Local Preview)
        step5(Video Decoding)
        step6(Video Post-processing)
        step7(Video Rendering Display)

        step1 --> step2 --> step3 --> step4 --> step5 --> step6 --> step7
    end

    subgraph network_module [Network Module]
        step8(Join Channel)

        step7 --> step8
    end