flowchart TD
    A[User Opens the App] -->|RTCEngine.create| B[Video SDK Initialization]
    B -->|Engine.enableVideo| C(Engine.joinChannel)
    C -->|Engine.on("joinChannelSuccess")| D[Host (Starting the Broadcast)]
    D --> E[Host publishes video stream using Publish function]
    E --> F[Send data stream function is triggered]
    F --> G[Host sets up local video view Widget = RtcLocalView.SurfaceView]
    G --> H[Join Broadcast (User Side)]
    E --> I[Engine.on("userJoined")]
    I --> J[Host subscribes to incoming video streams using Subscribe]
    J --> K[Host sets up remote video views Widget = RtcRemoteView.SurfaceView]
    K --> L[User Leaves the Broadcast]
    L --> M[Engine.leave'.leaveChannel]