flowchart TB
    subgraph clientA["Client A"]
        appA[("App A")]
        sdkA[("SDK A")]
        sdkA --> appA
    end
    subgraph clientB["Client B"]
        appB[("App B")]
        sdkB[("SDK B")]
        sdkB --> appB
    end
    captureA["Audio/Video Capture & Encoding - Client A"]
    captureB["Audio/Video Capture & Encoding - Client B"]
    appA --> captureA
    appB --> captureB

    encryptA["Encrypt & Transmit - Client A"]
    captureA --> encryptA

    subgraph edgeServerA["Edge Server A"]
        receiveA["Receive & Secure - Edge Server A"]
    end
    subgraph edgeServerB["Edge Server B"]
        decryptB["Decrypt & Transmit - Edge Server B"]
    end

    encryptA --> receiveA --> edgeServerB --> decryptB --> sdkB

    decodeB["Receive & Decode at Client B"]
    sdkB --> decodeB