flowchart TB
    subgraph Upstream ["Upstream Track (Sending End)"]
        input[("Input Source")]
        beauty["Beauty Filter"]
        virtualbg["Virtual Background"]
        videoLink["Video Link"]
        audioLink["Audio Link"]
        agora["Agora SD-RTN™️"]
        input --> beauty
        beauty --> virtualbg
        virtualbg --> videoLink
        virtualbg --> audioLink
        videoLink --> agora
        audioLink --> agora
    end

    subgraph Downlink ["Downlink Track (Receiving End)"]
        videoDecoder[("Video Decoder")]
        audioCodec[("Audio Codec")]
        filters[("Filters")]
        superRes["Super Resolution"]
        spatialSound["Spatial Sound Effects"]
        renderPlayback["Render/Playback"]
        videoDecoder --> filters
        audioCodec --> filters
        filters --> superRes
        filters --> spatialSound
        superSet --> renderPlayback
        spatialSound --> renderPlayback
    end

    agora --> videoDecoder
    agora --> audioCodec