flowchart TB
    initiation("Initiation: Set Client Role as Host") --> groupA[Group A]
    initiation --> groupB[Group B]

    groupA -->|Join Channel| agoraCloud[Agora SD-RTN™ Cloud]
    groupB -->|Join Channel| agoraCloud

    groupA -->|Publish Audio| groupB
    groupB -->|Publish Audio| groupA

    agoraCloud -->|Subscribe Audio| groupA
    agoraCloud -->|Subscribe Audio| groupB