flowchart TB
    subgraph TokenServer["Implemented by you (Token Server)"]
        JoinChannel["Join a channel with authentication"]
        RenewToken["Renow token"]

        JoinChannel --> |Request token| ValidateUser[("Validate user against internal security")]
        ValidateUser --> GenerateToken[("Generate and return token")]
        RenewToken --> |Request fresh token| ValidateRequest[("Validate user request against internal logic")]
        ValidateRequest --> GenerateFreshToken[("Generate and return fresh token")]
    end

    subgraph App["App"]
        HandleCommunication["Handle communication between Token Server and SD-RTN"]
        AdjustActionsBasedOnToken["Adjust actions based on token validity and expiration events"]
    end

    subgraph SDRTN["Provided by Agora (SD-RTN)"]
        JoinChannelWithToken["Join a channel with uid, channel name, and token"]
        ValidateToken["Validate the token"]
        NotifyExpiration["Notify app token is expiring"]
    end

    TokenServer -.-> |Provide token| App
    App -.-> |Intermediary| SDRTN
    SDRTN -.-> |Token validation| App
    App -->|Handle token expiration| TokenServer