flowchart TB
  A[Open App] --> B[Create an instance of Agora Engine using Voice SDK]
  B --> C[Setup raw data processing]
  C --> D[Join a channel]
  D --> E[Process raw audio data]
  E --> F[Leave the channel]

  subgraph D1 [Join a channel]
    D1a[Register audio frame observer] --> D1b[Set audio frame parameters]
    D1b --> D1c[Retrieve authentication token]
    D1c --> D1d[Join communication channel]
  end

  subgraph E1 [Process raw audio data]
    E1a[Get raw data in callbacks] --> E1b[Send processed data back through callbacks]
  end

  subgraph F1 [Leave the channel]
    F1a[Unregister audio frame observer] --> F1b[Exit communication channel]
  end