sequenceDiagram
    participant User as User
    participant App as Application
    participant SDK as Agora SDK
    participant Network as SD-RTN

    User->>App: Open app
    User->>App: Start call
    App->>SDK: AgoraRtcEngineKit.sharedEngine
    App->>SDK: agoraEngine.setClientRole(broadcaster)
    App->>SDK: agoraEngine?.joinChannel
    loop Handling Call
        SDK->>Network: Stream data
        Network-->>SDK: Receive data
    end
    User->>App: Terminate call
    App->>SDK: agoraEngine.leaveChannel(nil)
    App->>SDK: AgoraRtcEngineKit.destroy()
    User->>App: Close application