flowchart TD
    A[User Opens the App] -->|AgoraRTC.createClient| B[Setting Event Listeners]
    B --> C[User Starts a Call]
    C -->|Retrieve Token| D[Join Channel]
    D -->|agoraEngine.join| E[Create Microphone Audio Track]
    E --> F[Publish Local Audio Track]
    E -->|AgoraRTC.createMicrophoneAudioTrack| F[agoraEngine.publish]
    F --> G[Handling Streaming]
    G -->|agoraEngine.on("user-published")| H[Play Audio Track]
    H -->|remoteAudioTrack.play| I[Data Streams]
    G --> I
    I --> J[User Leaves the Call]
    J -->|agoraEngine.leave| K[End Connection]