flowchart TB
    Start(Start) --> InitSDK(Initiate Video SDK)
    InitSDK --> EnableVideoModules(Enable Video Modules)
    EnableVideoModules --> SetChannelProfiles(Set Channel Profiles)
    SetChannelProfiles --> Authenticate(Authenticate)
    Authenticate --> SetUserRoles(Set User Roles)
    SetUserRoles --> InitVideoSetup(Initialize Video Setups)
    InitVideoSetup --> StreamData(Stream Data)
    StreamData --> CleanUp(Clean up Resources)
    Clean+Up --> End(End)

    subgraph Host
      InitVideoSetup --> LocalSetup[Initialize Local Video Setup]
      LocalSetup --> StreamData
    end

    subgraph Audience
      InitVideoSetup --> RemoteSetup[Initialize Remote Video Setup]
      RemoteabSetup --> StreamData
    end