flowchart TB
    A[User opens the app]
    B[App initializes the Video SDK engine]
    C[Video is enabled in the engine]
    D[User stops the preview, leaves the channel, and the SDK cleans up]
    E[User closes the app]
    F[Host starts a live streaming event]
    G[Sets role to broadcaster]
    H[Starts local video output]
    I[Joins the streaming channel and sends data stream]
    J[Audience joins the live streaming event as an audience]
    K[Audience joins the channel to view the stream]
    L[Audience retrieves and receives the streaming data]

    A --> B
    B --> C
    C --> D
    D --> E
    F --> G
    G --> H
    H --> I
    J --> K
    K --> L