flowchart TD
    A(User Opens App) -->|AgoraRTC.createClient| B(SDK Engine Initialized)
    B --> C[Host Starts Video and Local Media Streams]
    C --> D[Host Retrieves Auth Token]
    D --> E{Set Role as 'Host'}
    E --> F(Host Joins Channel)
    F --> G(Host Publishes Local Media to Channel)
    B --> H(Audience Joins Event)
    H --> I[Audience Retrieves Auth Token]
    I --> J{Set Role as 'Audience'}
    J --> K(Audience Joins Stream)
    K --> L(Audience Subscribes to Data Stream from Host)
    G --> M(Both Host and Audience Leave via agoraEngine.leave)
    L --> M
    M --> N{Software Interaction with Agora's SD-RTN}