flowchart TD
    A[Opens the app] --> B[Initiates Video SDK engine]
    B --> C[Starts video in the engine]
    C --> E[Closes app & cleans up local resources]

    F[Starts an ILS event] --> G[Starts local video]
    G --> H[Joins the channel]
    H --> I[Sends a data stream to the channel]

    J[Joins the ILS event] --> K[Views broadcast by channel hosts]
    K --> L[Joins the channel]
    L --> M[Retrieves streaming from the host] --> N[Receives data streams]
    N --> O[Stops local video and leaves the channel]