flowchart TB
    id1(["Set the client role"])
    id2(["Retrieve a token"])
    id3(["Join a channel"])
    id4(["Publish local video and audio"])
    id5(["Subscribe to video and audio published by the host"])
    
    id1 --> id2 --> id3 --> id4 & id5