flowchart TD
    Server[Server retrieves AccessToken] --> |1| AccessToken[AccessToken]
    AccessToken --> |2| Laptop[Laptop]
    AccessToken --> |2| Desktop[Desktop Computer]
    AccessToken --> |2| Smartphone[Smartphone]
    Laptop --> Agora
    Desktop --> Agora
    Smartphone --> Agora
    Agora[Agora Platform]