flowchart TD
    A[Join a channel with authentication] --> B[Receive and use the new or renewed token for accessing channels via the Agora system]
    C[Renew token] --> B
    B --> D[Join a channel]
    B --> E[Manage callbacks and token expiry events]

    subgraph t1["Token server (Implemented by you)"]
    A
    C
    end

    subgraph t2["App"]
    B
    end

    subgraph t3["Provided by Agora (SD-RTN)"]
    D
    E
    end