classDiagram
    class PlantUML_Screenshot {
        Header : "Welcome to PlantUML!"
        Instructions_and_Examples : "Examples to start with simple UML diagrams"
        Further_Information_Link : "https://plantuml.com"
        Version_Information : "PlantUML 1.2023.12"
        Error_Message : "Error in including file agora_skin.iuml"
    }