flowchart TD
    A[User] -->|Login| B[Web Server]
    B --> C[App]
    C -->|Auth Request| D[SD-RTN]
    A -->|Request to Create Channel| C
    C -->|Create Channel| D
    D -->|Notification 101| C
    C -->|Authenticate Notification| C
    C -->|Channel Operation| E[200 OK]
    A -->|Request to Close Channel| C
    C -->|Close Channel| D
    D -->|Notification 102| C
    C -->|Authenticate Notification| C
    C -->|Channel Close Status| E
    A -->|Logout| B
    B --> C
    C -->|Inform Logout| D