flowchart TD
    StartApp[Start the app] --> SelectChannel[Select a channel to join]
    SelectMale[./img]
    SelectChannel --> SetRegion[Set SD-RTN region in the Agora engine configuration]
    SetRegion --> InitAgora[Initiate the Agora engine]
    InitAgora --> ConnectSDRTN[Connect to SD-RTN in a specific region]
    ConnectSDRTN --> SuccessResponse[Success response]
    SuccessResponse --> JoinChannel[Join a channel with user Id, channel name, and token]
    JoinChannel --> JoinAccepted[Join accepted]

    classDef userActions fill:#f9f,stroke:#333,stroke-width:2px;
    class StartApp,SelectChannel userActions;

    classDef appProcesses fill:#ccf,stroke:#333,stroke-width:2px;
    class SetRegion,InitAgora,ConnectSDRTN,SuccessResponse,JoinChannel,JoinAccepted appProcesses;