flowchart TB
    A[Opening the App] --> B[Creation and Configuration]
    B --> C[Setup of Raw Data Processing]
    C --> D[Joining a Channel]
    D --> E[Processing Raw Audio and Video Data]
    E --> F[Leaving the Channel]
    F --> G[Closure]