flowchart TB

    A["User Opens and Closes Game"]
    B["Video SDK Initiations and Settings"]
    C["Joining and Leaving Calls"]
    D["Resource Management"]
    E["Agora"]
    F["SD-RTN"]

    A -->|Start| B
    B -->|Setup Complete| C
    C -->|Operations Complete| D
    D -->|End| A

    B -->|Init SDK Engine| IRtcEngineGetEngine["IRtcEngine.GetEngine()"]
    IRtcEngineGetEngine --> EnableVideo["EnableVideo()"]
    EnableVideo --> EnableVideoObserver["EnableVideoObserver()"]
    EnableVideoObserver --> C

    C -->|Join Channel| JoinChannelByKey["JoinChannelByKey()"]
    JoinChannelByKey --> OnUserJoined["OnUserJoin()"]
    OnUserJoined --> RemoteViewSetForUser["RemoteView.SetForUser(uid)"]
    RemoteViewSetForUser --> DataStreamHandling["Data Stream Handling"]
    DataFundling --> SFLeaveChannel["leaveChannel()"]
    SFLeaveChannel --> DisableVideo["DisableVideo()"]
    DisableVideo --> DisableVideoObserver["DisableVideoObserver()"]
    DisableVideoObserver --> D

    D -->|Clean Resources| destroy["destroy()"]
    destroy --> A

    B --> E
    E --> F
    F --> C