sequenceDiagram
    participant U as User
    participant A as App
    participant AE as Agora Engine
    participant AVS as Agora Video SDK
    participant SDRTN as Agora SD-RTN

    U->>A: Open App
    A->>AVS: Initiate Agora Video SDK engine
    AVS->>AE: createInstance()
    AE->>A: enableVideo()
    AE->>A: setupLocalVideo(VideoCanvas)
    A->>AVS: Retrieve authentication token to join channel
    AE->>SDRTN: joinChannel()
    SDRTN->>AE: Acknowledge Join
    AE->>SDRTN: setupRemoteVideo(VideoCanvas)
    loop Streaming
        SDRTN->>AE: Receive and send data stream
    end
    U->>AE: Leave the call
    AE->>SDRTN: leaveChannel()
    U->>A: Close App
    AE->>A: destroy()