flowchart TB
    User([User])
    Host([Host])
    App[App]
    SDK[Video SDK]
    Engine[RTC Engine]
    API[API]
    LocalView[RtcLocalView.SurfaceView]
    RemoteView[RtcRemoteView.SurfaceView]
    
    User -->|Opens the app| App
    App -->|Uses SDK| SDK
    SDK --> Engine -->|Enables Video| Engine
    Engine -->|Joins a channel| Join_Success[Engine.on('joinChannelSuccess')]
    Join_Success -->|Channel Joined| Interactions[User/Host Interaction]

    Host -->|Starts broadcast| Start_Broadcast
    Start_Broadcast -->|Publishes broadcast & sends data stream| Publish_Broadcast
    Publish_Broadcast --> LocalView
    LocalView -->|Notification of user join| Notification[Engine.on('userJoined')]
    Notification -->|Subscribes to event| Subscription
    Subscription -->|Receives data stream| RemoteView

    Interactions -->|User can leave| Leave_Broadcast[Engine.leaveChannel]
    Leave_Broadcast -->|User leaves| End[End of Interaction]

    classDef startstop fill:#f9f,stroke:#333,stroke-width:2px;
    class Start_Broadcast,End startstop;