flowchart TD
    A([User and Your app]) --> B(Open App)
    B --> C(Initiate the Video SDK engine)
    C --> D(Set the required event listeners)
    D --> E(Start call)
    E --> F(Retrieve authentication token to join channel)
    F --> G(Join a channel)
    G --> H(Join accepted)
    H --> I(Create local media tracks)
    I --> J(Push local media merchies to the channel)
    J --> K(Retrieve streaming from the other user)
    K --> L(Play remote media tracks)
    L --> M(Leave call)
    M --> N(SD-RTN)