flowchart TD
    A([Start]) --> B(Open App)
    B --> C(Initiate the Agora Video SDK engine)
    C --> D(Setup the local video stream)
    D --> E(Widget = RtcLocalView.SurfaceView())
    E --> F(Retrieve authentication token to join channel)
    F --> G(Join the channel)
    G --> H(Retrieve streaming from the other user)
    H --> I(Receive and send data stream)
    I --> J(Leave the channel)
    J --> K(Clean up local resources)
    K --> L([End])