flowchart TB
    userOpenApp[User Open App] --> initiateSDK[Initiate the Video SDK Engine: agoraEngine = AgoraRTC.createClient]
    initiateSDK --> startVideo[Start Video in the Engine: agoraEngine.init]
    startVideo --> startLocalMedia[Start Local Media]
    startLocalMedia --> createStream[localStream = AgoraRTC.createStream]
    createStream --> initStream[localStream.init]
    initStream --> playStream[localStream.play]
    playStream --> userStartCall[User Starts a Call]
    userStartCall --> retrieveToken[Retrieve Authentication Token to Join Channel]
    retrieveToken --> joinChannel[Join the Channel: agoraEngine.join]
    joinChannel --> pushLocalMedia[Push Local Media to the Channel: agoraEngine.publish]
    pushLocalMedia --> retrieveOtherUserStream[Retrieve Streaming from the Other User]
    retrieveOtherUserStream --> streamAdded[agoraEngine.on("stream-added")]
    streamAdded --> subscribeStream[agoraEngine.subscribe]
    subscribeStream --> streamSubscribed[agoraEngine.on("stream-subscribed")]
    streamSubscribed --> dataStreams[Receive and Send Data Streams]
    dataStreams --> userLeavesCall[User Leaves Call]
    userLeavesCall --> leaveChannel[Leave the Channel: agoraEngine.leave]