flowchart LR
    A[Start App] --> B[Open Video Call as Host]
    B --> C[Initiate Agora Video SDK]
    C --> D[AgoraRtcEngineKit.sharedEngine]
    D --> E[agoraEngine.enableVideo()]
    E --> F[agoraEngine.setClientRole(.broadcaster)]
    F --> G[agoraEngine.setupLocalVideo(videoCanvas)]
    G --> H[agoraEngine.setupRemoteVideo(videoCanvas)]
    H --> I[agoraEngine.joinChannel]
    I --> J[Video Call In Progress]
    J --> K[agoraEngine.leaveChannel(nil)]
    K --> L[End Call]
    L --> M[AgoraRtcEngineKit.destroy()]
    M --> N[Close App]